---
- name: create namespace CZERTAINLY
  kubernetes.core.k8s:
    namespace: default
    state: present
    src: /etc/ansible/roles/host-config/files/namespace-czertainly.yaml

# this will always overwrite target file and we are ignoring change
- name: create secret for harbor
  ansible.builtin.shell:
    cmd: /var/lib/rancher/rke2/bin/kubectl create secret -n czertainly docker-registry {{ docker.secret }} --docker-server={{ docker.server }} --docker-username={{ docker.username }} --docker-password={{ docker.password }} --docker-email={{ docker.email }} --dry-run='client' -o yaml > /root/install/docker-secret.yaml
  changed_when: false

# this apply only when changed - there must be more elegant way, but
# problem with dockerconfigjson is that thre is 2 times base64 encoded
# password
#
- name: register secret for harbor
  kubernetes.core.k8s:
    namespace: czertainly
    state: present
    src: /root/install/docker-secret.yaml

# Download sample trusted-certificates.pem file
- name: Download sample trusted-certificates.pem file
  ansible.builtin.get_url:
    url: https://github.com/3KeyCompany/CZERTAINLY-Helm-Charts/raw/develop/samples/trusted-certificates.pem
    dest: /home/czertainly/trusted-certificates-sample.pem
    force_basic_auth: yes
    backup: no
    owner: czertainly
    group: czertainly
    mode: 0644
  tags:
    - czertainly
    - czertainly_trusted_certificates
    - czertainly_app

# Download sample values.yaml file
# - name: Download default values.yaml file
#   shell: helm show values oci://harbor.3key.company/czertainly-helm/czertainly > /home/czertainly/czertainly-values-default.yaml
#   args:
#     creates: /home/czertainly/czertainly-values-default.yaml
#   tags:
#     - czertainly
#     - czertainly_values
#     - czertainly_app

#- debug: var=ansible

- name: Create openssl.conf
  template:
    src: "openssl.j2"
    dest: "/home/czertainly/openssl.cnf"
    owner: czertainly
    group: czertainly
    mode: '0644'
  tags:
    - czertainly
    - czertainly_app
    - czertainly_openssl_cnf

- name: create values file
  template:
    src: "czertainly-values.yaml.j2"
    dest: "/home/czertainly/czertainly-values.yaml"
    owner: czertainly
    group: czertainly
    mode: '0644'
  tags:
    - czertainly
    - czertainly_app

#helm install --namespace czertainly -f /home/czertainly/czertainly-values-default.yaml $PULL_SERCRET --set-file trusted.certificates=/home/czertainly/trusted-certificates-sample.pem czertainly-tlm oci://harbor.3key.company/czertainly-helm/czertainly

#   helm install [NAME] [CHART] [flags]

      #- name: install czertainly
      #  kubernetes.core.helm:
      #    values_files: /home/czertainly/czertainly-values.yaml
      #    release_namespace: czertainly
      #    release_name: czertianly-tlm
      #    chart_ref: oci://harbor.3key.company/czertainly-helm/czertainly
