---
# tasks file for czertainly

- name: Install open-vm-tools packages
  ansible.builtin.apt:
    name: open-vm-tools
    state: present
    update_cache: false
  tags:
    - apt-packages
    - virt-packages
  when: false # TODO check for virtualization type but also conflict with idea of creating appliance in VirtualBox and exporting for others

- name: Allow GIT_ variables in sshd_config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regex: '^AcceptEnv'
    line: 'AcceptEnv LANG LC_* GIT_*'
  notify: restart sshd
  tags:
    - ssh

- name: Install and configure postgres
  ansible.builtin.include_tasks: postgres.yml
  tags:
    - postgress

# this causes postgres (and any other handler) to restart
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
