---
# tasks file for czertainly

- name: Install open-vm-tools packages
  apt:
    name: open-vm-tools
    state: latest
    update_cache: no
  tags:
    - czertainly
    - czertainly_packages
  when: false # TODO check for virtualization type but also conflict with idea of creating appliance in VirtualBox and exporting for others

- name: install and configure postgres
  include: postgres.yml

- name: install CZERTAINLY
  include: czertainly.yml