---
# tasks file for czertainly

- name: Install open-vm-tools packages
  apt:
    name: open-vm-tools
    state: latest
    update_cache: no
  tags:
    - czertainly
    - czertainly_packages
  when: false # TODO check for virtualization type but also conflict with idea of creating appliance in VirtualBox and exporting for others

- name: install and configure postgres
  include: postgres.yml

# Download sample trusted-certificates.pem file
- name: Download sample trusted-certificates.pem file
  ansible.builtin.get_url:
    url: https://github.com/3KeyCompany/CZERTAINLY-Helm-Charts/raw/develop/samples/trusted-certificates.pem
    dest: /home/czertainly/trusted-certificates-sample.pem
    force_basic_auth: yes
    backup: no
    owner: czertainly
    group: czertainly
    mode: 0644
  tags:
    - czertainly
    - czertainly_trusted_certificates
    - czertainly_app

# Download sample values.yaml file
- name: Download default values.yaml file
  shell: helm show values oci://harbor.3key.company/czertainly-helm/czertainly > /home/czertainly/czertainly-values-default.yaml
  args:
    creates: /home/czertainly/czertainly-values-default.yaml
  tags:
    - czertainly
    - czertainly_values
    - czertainly_app

- name: Set owner and permissions of default values.yaml file
  ansible.builtin.file:
    path: /home/czertainly/czertainly-values-default.yaml
    owner: czertainly
    group: czertainly
    mode: '0644'
  tags:
    - czertainly
    - czertainly_values
    - czertainly_app

- name: Create openssl.conf
  template:
    src: "openssl.j2"
    dest: "/home/czertainly/openssl.cnf"
    owner: czertainly
    group: czertainly
    mode: '0644'
  tags:
    - czertainly
    - czertainly_app
    - czertainly_openssl_cnf
