---
# tasks file for postgres

# Install Postgres
- name: install postgres package
  apt:
    name:
      - postgresql
      - python3-psycopg2 # needed for ansible postgress modules
    state: latest
    cache_valid_time: 86400
  tags:
    - apt-packages

- name: enable Postgres
  ansible.builtin.systemd:
    name: postgresql
    enabled: yes
  tags:
    - postgres_enable

- name: Postgresql should listen on all ports
  lineinfile: dest="/etc/postgresql/13/main/postgresql.conf"
              regexp="^listen_addresses"
              line="listen_addresses = '*'"
              state=present
  tags:
    - postgres_listen
  notify:
    restart postgresql

- name: update pg_hba.conf. Grant user czertainly access to all databases on server.
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/13/main/pg_hba.conf
    contype: host
    users: "{{ postgres.username }}"
    source: all
    databases: all
    method: md5
    create: true
  tags:
    - postgres_pg_hba
    - postgress_czertainly_remote_access
  notify:
    restart postgresql

- name: create czertainlydb
  become: yes
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ postgres.database }}"
  tags:
    - postgress_czertainly_db

- name: create czertainlyuser
  become: yes
  become_user: postgres
  community.postgresql.postgresql_user:
    db: "{{ postgres.database }}"
    name: "{{ postgres.username }}"
    password: "{{ postgres.password }}"
  when: not ansible_check_mode # will fail in check mode if db isn't present
  tags:
    - postgress_czertainly_user

- name: grant ALL priv to czertainlydb to czertainlyuser
  become: yes
  become_user: postgres
  community.postgresql.postgresql_privs:
    db: postgres
    privs: ALL
    type: database
    obj: "{{ postgres.database }}"
    role: "{{ postgres.username }}"
  when: not ansible_check_mode # will fail in check mode if db isn't present
  tags:
    - postgress_czertainly_grant_all
